ALTER TABLE articles ADD COLUMN IF NOT EXISTS category VARCHAR(20);
ALTER TABLE articles ADD COLUMN IF NOT EXISTS tags VARCHAR(500);
ALTER TABLE articles ADD COLUMN IF NOT EXISTS reading_time_minutes INT;
